### ISSUE TITLE
Zmiana API magazynów

### ISSUE THREAD

**Issue by Haseoo** [IUI-januszex/paka-warehouse#1]
Należałoby zmienić pole odpowiedzi przy pobieraniu magazynów  na z idLocal/GlobalWarehouse na po prostu  idWarehouse. Pozwoli to na uniknięcie dublikowania kodu z tego powodu, ponieważ większość pól jest identyczna.
@majeklDeSanta

**Comment by majeklDeSanta** [comment]
No nie wiem czy to dobre posunięcie, gdy masz taki idWarehouse to już nie wiesz czy to jest globalny czy lokalny magazyn

**Comment by Haseoo** [comment]
Wiem, ponieważ żeby go pobrać muszę najpierw wiedzieć skąd po pobrać (są inne adresy endpontów), a więc po pobraniu nadal będę wiedział co to za magazyn.

**Comment by Haseoo** [comment]
I co z tą sprawą @majeklDeSanta?

**Comment by majeklDeSanta** [comment]
do wtorku będzie zrobione, bo teraz ostatnio się na tych e-mail skupiłem

sob., 27 lis 2021 o 20:39 Dawid Szymkiewicz ***@***.***>
napisał(a):

**Comment by majeklDeSanta** [comment]
Done, przepraszam że tak długo :(
