### ISSUE TITLE
Dlaczego metody post i put mają id w request body?

### ISSUE THREAD

**Issue by Haseoo** [IUI-januszex/paka-warehouse#4]
Chyba nie powinny mieć

**Comment by Haseoo** [comment]
jest to skończone @majeklDeSanta?

**Comment by majeklDeSanta** [comment]
Tak, zakończyłem to przed wczoraj i napisałem do ciebie na Discord

pt., 3 gru 2021, 22:52 użytkownik Dawid Szymkiewicz <
***@***.***> napisał:
